"use client";
import { useState } from "react";
import { Sparkles } from "lucide-react";
import { Dialog } from "./dialog";
import { saveTemplate } from "@/lib/repository";
import { generateTemplateDraft, type TemplateGoal, type TemplateService, type TemplateTone } from "@/lib/business";
export function TemplateDialog({ownerId,onClose,onSaved}:{ownerId:string;onClose:()=>void;onSaved:()=>void}){
  const[data,setData]=useState({title:"",category:"Semua bisnis",content:"Halo {{contact_name}}, saya dari Nexty Labs. Kami ingin membantu {{company_name}} mengembangkan bisnis {{category}} secara digital.",isDefault:false}),[generator,setGenerator]=useState<{goal:TemplateGoal;service:TemplateService;tone:TemplateTone}>({goal:"INTRODUCTION",service:"ALL",tone:"FRIENDLY"}),[error,setError]=useState("");
  function makeDraft(){const draft=generateTemplateDraft(generator);setData(current=>({...current,...draft}));setError("")}
  return <Dialog title="Buat pesan siap pakai" onClose={onClose}><form className="form-grid" onSubmit={async event=>{event.preventDefault();try{await saveTemplate(ownerId,data);onSaved()}catch(e){setError(e instanceof Error?e.message:"Pesan belum bisa disimpan.")}}}><section className="generator-box wide"><div><Sparkles size={18}/><span><b>Buat draf otomatis</b><small>Pilih kebutuhan pesan. Hasilnya masih bisa diperiksa dan diubah.</small></span></div><div className="generator-options"><label>Tujuan pesan<select value={generator.goal} onChange={e=>setGenerator({...generator,goal:e.target.value as TemplateGoal})}><option value="INTRODUCTION">Perkenalan pertama</option><option value="FOLLOW_UP">Menanyakan kembali</option><option value="CONSULTATION">Mengajak konsultasi</option><option value="OFFER">Memberikan penawaran</option></select></label><label>Layanan yang ditawarkan<select value={generator.service} onChange={e=>setGenerator({...generator,service:e.target.value as TemplateService})}><option value="ALL">Semua layanan Nexty</option><option value="WEBSITE_APP">Website & aplikasi</option><option value="BRANDING">Design & branding</option><option value="IOT">Internet of Things</option></select></label><label>Gaya bahasa<select value={generator.tone} onChange={e=>setGenerator({...generator,tone:e.target.value as TemplateTone})}><option value="FRIENDLY">Ramah dan profesional</option><option value="SHORT">Singkat dan langsung</option><option value="FORMAL">Lebih formal</option></select></label></div><button type="button" className="secondary" onClick={makeDraft}><Sparkles size={16}/>Buat draf</button></section><label>Nama pesan<input required value={data.title} onChange={e=>setData({...data,title:e.target.value})} placeholder="Perkenalan usaha kuliner"/></label><label>Cocok untuk usaha<input value={data.category} onChange={e=>setData({...data,category:e.target.value})} placeholder="Kafe, klinik, atau semua bisnis"/></label><label className="wide">Isi pesan<textarea rows={9} required value={data.content} onChange={e=>setData({...data,content:e.target.value})}/><small>Gunakan {'{{contact_name}}'}, {'{{company_name}}'}, dan {'{{category}}'} agar isinya diganti otomatis.</small></label><label className="check wide"><input type="checkbox" checked={data.isDefault} onChange={e=>setData({...data,isDefault:e.target.checked})}/>Gunakan sebagai pilihan utama</label>{error&&<div className="error-box wide">{error}</div>}<div className="modal-actions wide"><button type="button" className="secondary" onClick={onClose}>Batal</button><button className="primary">Simpan pesan</button></div></form></Dialog>
}
